### PR TITLE
 issue importing from Android Studio 1.1.0 & add .gitignore & bump minSd...

### PR DESCRIPTION
**Pull request by sreev**
...k from 8 to 11

issue importing from Android Studio 1.1.0
https://github.com/googlesamples/android-NetworkConnect/issues/2

add .gitignore
https://github.com/googlesamples/android-NetworkConnect/issues/3

bump up minSdkVersion from 8 to 11 (android v3)
https://github.com/googlesamples/android-NetworkConnect/issues/4

### CODE REVIEW

**Comment by sreev** [comment]
Signed CLA.
Git Committed already, cannot change e-mail, now.

**Comment by keyboardsurfer** [comment]
Thanks for the pull request. Please either update the email address on the commit(s), sign the CLA with the corresponding email address or create a new pull request with the correct address. Otherwise we won't be able to accept your contribution.

**Comment by sreev** [comment]
Hi Benjamin,
Adding e-mail to git commits, makes it public visible. Not safe.So, i added this e-mail (the e-mail i use on git for this commit).In the CLA, i added my git username (sreev).
Your this process seems a bit out of the normal.What is the ultimate intention behind it ?
I found, the similar change is needed for other examples apps as well.
Thanking you.

With Regards
Sree 

```
 On Thursday, March 5, 2015 5:41 AM, Benjamin Weiss <notifications@github.com> wrote:
```

 Thanks for the pull request. Please either update the email address on the commit(s), sign the CLA with the corresponding email address or create a new pull request with the correct address. Otherwise we won't be able to accept your contribution.—

**Comment by tjohns** [comment]
sreev: CLAs are used by many large open source projects, including Apache, Python, Canonical, Eclipse, etc. See http://en.wikipedia.org/wiki/Contributor_License_Agreement for a partial list.

We require the email address to be correct, because GitHub is not our system of record. Once your commit is exported to our internal Git repository, we still need a way to track it and ensure that you've signed the CLA. The only field that Git gives us to do this is the email address.

Similarly, replying to this thread via email is not sufficient, because (again) GitHub is not our system of record and that information is not preserved in Git's metadata.

You can update your commit by using "git commit --amend --reset-author".

**Comment by tjohns** [comment]
On second thought, I'm going to go ahead and close this PR, since these are issues that need to be fixed across multiple samples, and the changes are simple. It's easier if I just address these bugs upstream, that way we can get everything fixed simultaneously. (We have some tools that allow us to bulk-edit all the samples simultaneously.)

That said, thanks for the contribution. I know the CLA adds some extra hoops to jump through, but we do appreciate it.

**Pull request closed without merging**
